import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sideBar/sideBar";
import HeaderBar from "@/components/Header/HeaderBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const chatId: number = 423424234;
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <main style={{ backgroundColor: "#212121" }} className="min-h-screen ">
          <HeaderBar chatID={chatId} />
          {children}
          <SideBar />
        </main>
      </body>
    </html>
  );
}
